# @name signin
POST http://localhost:8081/api/v1/auth/signin
Content-Type: application/json

{
    "usuario": "admin",
    "senha": "admin"
}

###
@token = {{signin.response.body.*}}

### POST /api/v1/cidade
POST http://localhost:8081/api/v1/cidades
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Joinville",
    "estado": "Santa Catarina"
}

### GET /api/v1/clientes
GET http://localhost:8081/api/v1/cidades
Authorization: Bearer {{token}}

### GET /api/v1/clientes
GET http://localhost:8081/api/v1/clientes
Authorization: Bearer {{token}}

### POST /api/v1/clientes
POST http://localhost:8081/api/v1/clientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Mariazinha",
    "endereco": "Rua lululul 200",
    "dataNascimento": "2024-04-23",
    "cidade": {
        "id": 1,
        "nome": "Joinville"
    }
}

### PUT /api/v1/clientes
PUT http://localhost:8081/api/v1/clientes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Zezinho da Silva",
    "endereco": "Rua lalalalla 100",
    "dataNascimento": "2024-04-17"
}


### DELETE /api/v1/clientes
DELETE http://localhost:8081/api/v1/clientes/1
Authorization: Bearer {{token}}
